"use client"

import Navbar from "./Components/Navbar";
import "./globals.css";
import { Provider } from "react-redux"
import store from "../app/Redux/store"
import SetUser from "./Auth/setUser";
import Toast from "./Auth/Toast";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store} >
          <Toast />
          <SetUser />
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
